
# html lang
language: en

# 导航栏 开头不带斜杠
menu:
  博客: ''
  标签云: tags
  关于: about

# 建议页数大于1开启
paginator: false

# 头部
header:
  blank: false     # 头部链接是否新标签页打开

# 文章列表
list:
  date: true       # 文章列表是否显示日期
  wordcount: true   # 是否显示字数统计

# 脚部
footer:
  display: false               # 是否显示footer
  context: "© smallyu.net"     # footer内容

# 文章页
post:
  title_h1: false               # 文章是否使用 h1 标题
  blank: false                 # 文章是否新标签页打开
  backHome: false              # 文章末尾是否显示返回首页
  backhome_right: false        # 返回首页内容是否右对齐
  backHome_hr: false           # 返回首页前是否显示分割线
  backHome_prefix: "↶ "        # 返回首页的前缀内容
  backHome_content: "返回首页"   # 返回首页的主体内容
  backHome_suffix: ""          # 返回首页的后缀内容

# 标签云
tags:
  all: true       # 标签云页面是否显示全部标签

google_analysis_id: UA-0000

version: 1
debug: false
